---
# tasks file for web
- name: update debian
  apt:
    update_cache=yes
- name: desinstall  apache2
  apt:
    name: apache2
    state: absent
- name: install  nginx
  apt:
    name: nginx
    state: present
- name: install  mysql
  apt:
    name: mysql-server
    state: present
#- name: supprime default
#  shell: rm /etc/nginx/sites-available/default
#- name: supprime default
#  shell: rm /etc/nginx/sites-enabled/default
  #file:
  #  path: /etc/nginx/sites-available/default
  #  state: absent
- name: restart nginx
  systemd:
    name: nginx
    state: reloaded
- name: installation php
  include: php.yml
  notify: service php
- git:
    repo: 'https://github.com/wikimedia/mediawiki.git'
    dest: /var/www/html/mediawiki
- name: conf nginx
  include: nginxconf.yml