---
# tasks file for web
- name: clean machine
  include: clean.yml
- name: install docker
  include: docker.yml
- name: install/run container mediawiki
  include: img-mediawiki.yml
- name: install/run container mariadb
  include: img-mariadb.yml