---
# tasks file for nginx
- name: install php
  apt:
    name: "{{item}}"
    state: installed
  with_items: "{{stack_php}}"

- lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='post_max_size[\s]?=' line='post_max_size={{ php_post_max_size }}'
- lineinfile:
    path: /etc/php/7.0/fpm/php.ini
    regexp: 'date.timezone[\s]?='
    line: '{{php_timezone}}'
- lineinfile:
    path: /etc/php/7.0/fpm/php.ini
    regexp: 'upload_max_filesize[\s]?='
    line: '{{php_upload_max_filesize}}'
- lineinfile:
    path: /etc/php/7.0/fpm/php.ini
    regexp: 'memory_limit[\s]?='
    line: '{{php_memory_limit}}'

